######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 2 05:56:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += NDimArray.hpp
SOURCES += NDimDemo.cpp
