######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 2 05:56:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
#CONFIG += debug

# Input
HEADERS += PermArray.hpp Global.hpp NPerm.hpp NDimArray.hpp NTuple.hpp BaseArray.hpp Iterators.hpp RangeSet.hpp SparseArray.hpp Array.hpp BasicArray.hpp
SOURCES += NDimDemo.cpp Array.cpp
